name: SonarQube analysis

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  Analysis:
    runs-on: [ 'self-hosted' , 'v1' ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Analyze with SonarQube
        run: sonar-scanner.bat -D"sonar.projectKey=test-sonarqube" -D"sonar.sources=." -D"sonar.host.url=${{ secrets.SQ_HOST_URL }}" -D"sonar.token=${{ secrets.SONAR_TOKEN }}"
